# Usando uma imagem Python específica
FROM python:3.11-slim

# Setando variáveis de ambiente
ENV DJANGO_ENV=prod

# Configurando o diretório de trabalho
WORKDIR /app

# Copiando os arquivos do projeto
COPY . /app/

# Instalando as dependências
RUN pip install -r requirements/requirements-prod.txt

# Rodando o servidor Django com Gunicorn para produção
CMD ["gunicorn", "app.wsgi:application", "--bind", "0.0.0.0:8000"]
